### ISSUE TITLE
Rails 4 support?

### ISSUE THREAD

**Issue by ryders** [jsmestad/rocket_shorts#2]
Hmmmmf!

Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    rocket_shorts (>= 0) ruby depends on
      actionpack (~> 3.0) ruby

```
rails (= 4.0.0) ruby depends on
  actionpack (4.0.0)
```

rocket_pants supports rails 4..

**Comment by jsmestad** [comment]
Yeah I have to update this. I would welcome a pull request btw.

**Comment by ryders** [comment]
Just cleaning a few things up. Looking at dates, this is clearly not anybody's priority by now 🤣
